### ISSUE TITLE
Data locations using manifest file

### ISSUE THREAD

**Issue by jjkoehorst** [ResearchObject/runcrate#54]
I am currently diving into CWLTool with modifying file locations into subfolders when using provenance.
The application currently only looks in `source = self.root / Path(“data”) / hash_[:2] / hash_` which might not be correct in the long run.

Perhaps an option could be to use the manifest file for this?

```
cat PROV_NO_INPUT_2/manifest-sha1.txt
27a9b1a98a2f8a3cfa6fc7f7390e1f33d9afc944  data/output/27/27a9b1a98a2f8a3cfa6fc7f7390e1f33d9afc944
10a02d2e45f8a8b6bd31e2455e0fc68327e86b43  data/output/10/10a02d2e45f8a8b6bd31e2455e0fc68327e86b43
f4e9c47034057ed1be718a080b8bee488586333a  data/output/f4/f4e9c47034057ed1be718a080b8bee488586333a
c0f2eb41e128804b6742359671875729a43e6d94  data/output/c0/c0f2eb41e128804b6742359671875729a43e6d94
d822fc5e5e405049db4529b8054c8042444c1576  data/output/d8/d822fc5e5
```

Which has the appropriate (sub) locations?

**Comment by simleo** [comment]
This is now fixed, thank you.

For this to keep working with the future version of CWLprov, the hash value of the file will still have to be available from the `prov:generalEntity` that is a `specializationOf` the parameter. See https://github.com/ResearchObject/runcrate/blob/64397c770c565ce7ce747a427a98a267828c61a4/src/runcrate/convert.py#L254

CC @mr-c
